revert aws sdk version from f0b76c45d081fe66bded44c60fa4560a879cb346 (#18695)
Due to failures in migration:

```
2024-11-19 17:16:15.916	picocli.CommandLine$ExecutionException: Error while calling command (public java.lang.Integer org.openmetadata.service.util.OpenMetadataOperations.migrate(boolean)): java.lang.NoClassDefFoundError: software/amazon/awssdk/checksums/SdkChecksum
2024-11-19 17:16:15.641	Updating bot users in case of an update on the JSON schema: [managed-aws]
2024-11-19 17:16:14.903	Updating services in case of an update on the JSON schema: [managed-aws]
```