Chore(UI): Fix the playwright test flakiness  (#25079)
* Fix the flakiness in specs AdvancedSearch.spec.ts, Table.spec.ts, CustomizeWidgets.spec.ts, Metric.spec.ts, DataContracts.spec.ts

* Fix failing tests

* Fix BulkImport spec failure

* Fix flakiness in Table.spec.ts

* Turn on trace for flakiness debug

* Fix the Data contract flakiness

* Revert "Turn on trace for flakiness debug"

This reverts commit 832d860657e6927dbbb3fd8c4a0ec5b1212139c6." --no-verify
error: pathspec 'on' did not match any file(s) known to git
error: pathspec 'trace' did not match any file(s) known to git
error: pathspec 'for' did not match any file(s) known to git
error: pathspec 'flakiness' did not match any file(s) known to git
error: pathspec 'debug

This reverts commit 832d860657e6927dbbb3fd8c4a0ec5b1212139c6.